name: smart_svg_image
description: "A Flutter widget that intelligently renders SVG images with enhanced compatibility. Automatically resolves common SVG rendering issues and provides seamless image display."
version: 0.0.2
homepage:  https://github.com/Shuvo8693/Smart-Svg-Image.git
repository:  https://github.com/Shuvo8693/Smart-Svg-Image.git
author: Shuvo Khondoker

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - test/assets/
